Issue #5: Update Graduation Dates
Hack-WashU/myhackwashu pull request #20
Opened 2022-06-25 20:34 UTC by eddiechoi00

## Patch Notes
### Feature Request
Changed graduation years.

## Additional Notes
Please ignore any of the other changes I made to accommodate running this locally. If you can't accept/merge the pull request as needed, you might have to make these changes (graduation years) manually; although it's a simple change I apologize for the inconvenience.

2022-06-25 22:54 UTC, jackheuberger commented
Closes #5

2022-06-25 22:57 UTC, jackheuberger requested changes

2022-06-25 22:57 UTC, jackheuberger commented on Makefile
> +	docker-compose down --volumes || true
Can you switch lines 18 and 19? Volumes should be brought down before being removed

2022-06-25 22:57 UTC, jackheuberger commented on app/hackathon_variables.py
> +HACKATHON_CONTACT_EMAIL = 'epsilon41@naver.com'
Remove this file from commit

2022-06-25 22:57 UTC, jackheuberger commented on applications/migrations/0040_auto_20220624_1615.py
> +    dependencies = [
Remove this file from commit

2022-06-25 22:57 UTC, jackheuberger commented on applications/migrations/0041_auto_20220624_1626.py
> +# Generated by Django 3.2.7 on 2022-06-24 21:26
Remove this file from commit

2022-06-25 22:57 UTC, jackheuberger commented on applications/models.py
> +YEARS = [(int(size), size) for size in ('2022 2023 2024 2025 2026'.split(' '))]
Are the frontend selection options generated automatically off of this list?

2022-06-26 00:11 UTC, eddiechoi00 commented on Makefile
> +	docker-compose down --volumes || true
Yes of course.

2022-06-26 00:11 UTC, eddiechoi00 commented on app/hackathon_variables.py
> +HACKATHON_CONTACT_EMAIL = 'epsilon41@naver.com'
Yessir

2022-06-26 00:13 UTC, eddiechoi00 commented on applications/models.py
> +YEARS = [(int(size), size) for size in ('2022 2023 2024 2025 2026'.split(' '))]
Yes I checke
<img width="445" alt="Screen Shot 2022-06-25 at 7 12 39 PM" src="https://user-images.githubusercontent.com/54597370/175794328-4de9db77-f658-4fe1-9c41-045a7efa8781.png">
d

2022-06-26 00:16 UTC, eddiechoi00 commented on applications/migrations/0040_auto_20220624_1615.py
> +    dependencies = [
The entire file?

2022-06-26 14:26 UTC, jackheuberger approved these changes
lgtm!

2022-06-26 14:26 UTC, merged